manchenkoff/nuxt-auth-sanctum

src/runtime/composables/useSanctumAuth.ts
this commit fix, when set `redirect.keepRequestedRoute = true` but still redirecting to config `redirect.onLogin`
=> fix: keepRequestedRoute

README.md, playground/pages/profile.vue, src/runtime/composables/useSanctumAuth.ts
This PR exposes the `refreshIdentity` method from the `useSanctumAuth` composable. This is useful in cases where one needs to refresh the authenticated user's data. It addresses manchenkoff/nuxt-auth-sanctum#24.
=> Exposes method to re-fetch authenticated user

src/runtime/httpFactory.ts
This is a very early PR to make this module compatible with [changes we expect to release in Nuxt v5](https://github.com/nuxt/nuxt/issues/25323).
In [Nuxt v3.7.0](https://github.com/nuxt/nuxt/releases/tag/v3.7.0) we added support for `import.meta.*` (see [original PR](https://github.com/nuxt/nuxt/pull/22428)) and we've been gradually updating docs and moving across from the old `process.*` patterned variables.
As I'm sure you're aware, these variables are replaced at build-time and enable tree-shaking in bundled code.
This change affects _runtime_ code (that is, that is processed by the Nuxt bundler, like vite or webpack) rather than code running in Node. So it really doesn't matter what the string is, …
=> fix: opt in to `import.meta.*` properties

playground/nuxt.config.ts, src/runtime/composables/useSanctumAuth.ts, src/runtime/httpFactory.ts
Fixes #44. From now on package check the current route and skips `redirect` if it is already done.
=> fix: prevent redirects to the same page

src/runtime/httpFactory.ts
Also fixes #44, but in this case, we prevent redirect when for some reason API returns a 401 response when we are on the `login` page.
=> fix: prevent redirect on 401 response from login page

CONTRIBUTING.md, playground/error.vue, playground/tsconfig.json, src/index.d.ts, src/module.ts, src/runtime/httpFactory.ts, src/runtime/middleware/sanctum.auth.ts, src/runtime/middleware/sanctum.global.ts, src/runtime/middleware/sanctum.guest.ts, src/types.ts, tsconfig.json
Closes #3. A new middleware was implemented for easier authentication rules set up for the whole application.
By default, this behavior is disabled and can be changed via configuration, more detailed description will be provided in [the documentation](https://manchenkoff.gitbook.io/nuxt-auth-sanctum).
**Checklist:**
-   [x] Requires documentation to be updated
=> feat: implemented global middleware

src/runtime/httpFactory.ts
Fixes #70. Removed redirects after getting 401 responses from the API since it should be done via business logic.
**Describe alternatives you've considered**
N/A
N/A
**Checklist:**
-   [ ] Requires documentation to be updated
=> fix: prevent infinite redirect for guests

package.json, src/runtime/httpFactory.ts, src/runtime/plugin.ts
Partially fixes #69, the plugin initialization method was changed in favor of passing the state of the user identity request from the server to the client to prevent another attempt to load the user when we receive 401 on the SSR side.
Also, we reset the plugin user state only when we receive 401 for user retrieval operation and not for other endpoints.
**Checklist:**
-   [ ] Requires documentation to be updated
=> fix: prevent multiple identity requests on init

playground/nuxt.config.ts, src/index.d.ts, src/runtime/middleware/sanctum.global.ts, src/types.ts
Closes #82 by enabling additional configuration for sanctum global middleware.
In this PR `excludeFromSanctum` option in the page meta was deprecated, now `sanctum.exlcluded` should be used.
**Checklist:**
-   [x] Requires documentation to be updated
=> feat!: added guest mode for global middleware

package.json, src/runtime/httpFactory.ts, yarn.lock
Fixes problem after using `set-cookie-parser` package introduced in #88.
=> fix: dropped extenal cookie parser to use h3

src/module.ts, src/runtime/middleware/sanctum.global.ts
Dropped support for deprecated field in favor to new `sanctum` section of a page metadata.
**Checklist:**
-   [ ] Backwards compatibility is maintained
-   [ ] Requires documentation to be updated
=> feat!: dropped support for excludeFromSanctum page meta

src/runtime/httpFactory.ts
Following up on #6, in this PR we introduce experimental support for Cloudflare workers that do not support `fetch` interface due to missing `credentials` field. 
Related issue - https://github.com/cloudflare/workers-sdk/issues/2514
**Checklist:**
=> fix: experimental support for cloudflare workers

src/runtime/httpFactory.ts
Closes #108 and probably related #6 (comments from @alecritson). 
Due to the Nuxt hack with the [`runWithContext`](https://nuxt.com/docs/api/composables/use-nuxt-app#runwithcontext) call for request/response interceptors, there was an edge case when cookies after refresh were not included in the result headers due to missing `await` keyword, thus CSRF token was missing or was used from the previous API response.
This PR changes how the Nuxt instance will be passed to each interceptor. Now each interceptor is wrapped with the current instance context instead of running a loop with one instance.
**Checklist:**
-   [x] Backwards …
=> fix: use updated csrf token on first login

src/config.ts, src/runtime/httpFactory.ts, src/runtime/types/options.ts
Closes #116 by providing a new configuration property that enables an automatic client redirection after getting 401 status code from the API.
To prevent an infinite loop I enable redirects only for CSR mode since SSR will always end up with the user re-initialization.
By default, to keep backward compatibility, `redirectIfUnauthenticated` is false. Also, user identity now will be reset not only on plugin initialization but whenever API returns 401 as well.
Updated configuration docs - [Configuration](https://manchenkoff.gitbook.io/nuxt-auth-sanctum/usage/configuration#available-options)
Updated error handling docs - [Error …
=> feat: configure redirect if unauthenticated

src/runtime/composables/useSanctumAuth.ts, src/runtime/httpFactory.ts, src/runtime/interceptors/cookie/response.ts, src/runtime/middleware/sanctum.auth.ts, src/runtime/middleware/sanctum.global.ts, src/runtime/utils/formatter.ts
Potentially fixes #109 by removing the trailing slash from the URL extracted from `useRoute()` call.
The same applies to all other route comparisons.
**Checklist:**
-   [x] Documentation is updated
=> fix: trim trailing slash on redirects

package.json, yarn.lock
Previous versions of `@nuxt/module-builder` produced incorrect types for files in the `runtime/` directory. Specifically, a `.d.ts` declaration paired with a `.mjs` file. This isn't correct - it should be either `.d.mts`  and `.mjs` or `.d.ts` and `.js`. 
For maximum compatibility, `@nuxt/module-builder` v0.8 switched to `.js` extension for files in `runtime/` directory.
With the latest Nuxt, this is now an error that removes correct plugin injection types.
Related PRs: https://github.com/nuxt/nuxt/pull/28480, https://github.com/nuxt/nuxt/pull/28593
See also https://github.com/nuxt/nuxt/issues/28672.
Add any other context or screenshots about the feature request here. …
=> fix: update to latest `@nuxt/module-builder`

src/config.ts, src/module.ts, src/runtime/composables/useSanctumAuth.ts, src/runtime/plugin.ts, src/runtime/types/options.ts, src/runtime/utils/constants.ts
Closes #162 by adding the following features:
- Use the `sanctum.appendPlugin` config key to enable the `append` operation instead of the default `prepend` for the plugin.
- Disable initial user request by changing `sanctum.client.initialRequest` to `false`. A separate method now is exposed in `useSanctumAuth` composable - `init`, which will be executed only once regardless of the selected SSR/CSR environment.
Since the plugin's `dependsOn` cannot be configured externally (due to module initialization scope), module options cannot be used either.
Now when we need to ensure that the sanctum client makes the initial user request only after some other plugins are loaded (e.g. i18n), …
=> feat: granular control over plugin load order and user request

src/runtime/interceptors/cookie/request.ts
Potentially closes #163 by using the `User-Agent` header from the client request to prevent session regeneration during the hashing process.
=> fix: keep same session on SSR requests

playground/nuxt.config.ts, src/runtime/httpFactory.ts, src/runtime/plugin.ts
This PR closes #176 by using the Nuxt instance context while setting default token storage in SSR mode.
=> fix: use nuxt app context for default token storage

src/runtime/httpFactory.ts, src/runtime/interceptors/common/request.ts, src/runtime/interceptors/cookie/request.ts, src/runtime/interceptors/token/request.ts
This PR closes #183 issue related to the request headers being built incorrectly during SSR requests. One of the possible reasons is the incorrect interface of the headers container, check for details here - https://github.com/nuxt/nuxt/issues/14268.
=> fix: prevent object merging with HeadersList

src/runtime/interceptors/common/request.ts, src/runtime/interceptors/cookie/request.ts, src/runtime/interceptors/token/request.ts
Should resolve #188 by overwriting the headers instead of setting new values on top of it.
=> fix: prevent concurrent update of request headers

package.json, pnpm-lock.yaml, src/runtime/httpFactory.ts, src/runtime/interceptors/common/request.ts, src/runtime/interceptors/cookie/request.ts, src/runtime/interceptors/token/request.ts, src/runtime/utils/headers.ts
After `ofetch 1.4.0` release that includes https://github.com/unjs/ofetch/pull/436, `nuxt-auth-sanctum` interceptors stopped working properly due to the usage of `HeadersInit` instead of `Headers` type.
This PR introduces a new helper that appends new headers to the existing `Header` collection. Should fix issues in #188 and #191.
=> fix: use normalized ofetch headers

package.json, pnpm-lock.yaml, src/runtime/httpFactory.ts
This PR introduces `ofetch` as actual dependency to prevent type misleading when working with Headers in the interceptors. 
However, if object was overwritten during custom interceptor in client's code, we do not expect `entries()` to be a part of the headers, so object logging will be applied.
=> disallow `ofetch` versions lower than `1.4.0`

playground/nuxt.config.ts, src/config.ts, src/module.ts, src/runtime/types/options.ts
Middlewares from modules have lower order from the ones in the middleware folder. This is a problem if we want to run an auth related global middleware.
For example, we want to run `sanctum:auth:global` to check if the user is authenticated before running a global middleware to check if the user has the right permissions.
This adds support for prepending the `sanctum:auth:global` middleware to the list of existing middleware, more info [here](https://nuxt.com/docs/api/kit/pages#addroutemiddleware).
```js
globalMiddleware: {
// Default value is false
prepend: true,
},
```
=> feat: add option to prepend the global middleware

src/runtime/interceptors/cookie/response.ts
Closes #298 by deduplicating `set-cookie` headers in the response of Nuxt SSR (H3) when multiple requests are made against Laravel API. All other headers are preserved and should not be omitted.
=> fix: deduplicate `set-cookie` headers on SSR response

src/runtime/composables/useLazySanctumFetch.ts, src/runtime/composables/useSanctumFetch.ts
Closes #305 by adding two new composables:
- `useSanctumFetch`
- `useLazySanctumFetch`
These composables provide the same functionality as `useFetch`/`useLazyFetch` but with preconfigured `sanctum` client to take care of CSRF, cookies, etc.
=> feat: added new composables to make requests

src/runtime/composables/useLazySanctumFetch.ts, src/runtime/composables/useSanctumFetch.ts
Fixes #308 by using `useAsyncData` instead of `useFetch` with custom client. The main reason is the different visibility of `useFetch` within Nuxt global namespace / module / layers. Thus, this composable is recommended only at the application level.
=> fix: migrated from useFetch to useAsyncData

playground/app/plugins/sanctum.hooks.ts, src/runtime/composables/useSanctumAuth.ts, src/runtime/plugin.ts, src/runtime/types/options.ts, src/templates.ts
Closes #324 by introducing new hooks to notify client code about fetching user identity:
- `sanctum:init`
- `sanctum:refresh`
=> 324-feature-hooks-identity-fetch-init-event

playground/app/plugins/sanctum.hooks.ts, src/runtime/composables/useSanctumAuth.ts, src/templates.ts
Closes #320 by introducing a new `sanctum:login` hook to notify client code about successful login event.
=> 320-feature-hooks-login-event

playground/app/plugins/sanctum.hooks.ts, src/runtime/composables/useSanctumAuth.ts, src/templates.ts
Closes #321 by introducing a new `sanctum:logout` hook which triggers when users log out.
=> 321-feature-hooks-logout-event

CONTRIBUTING.md, package.json, src/runtime/composables/useLazySanctumFetch.ts, src/runtime/composables/useSanctumFetch.ts, src/runtime/utils/fetch.ts
Closes #330 by introducing a new optional argument for `useSanctumFetch` and `useLazySanctumFetch` composables. Now we can pass options for `useAsyncData` used underneath and also keep the ability to pass `FetchOptions` for the client used inside of `useAsyncData` call handler.
=> feat(fetch)!: support AsyncDataOptions in sanctum fetch composables

src/runtime/interceptors/common/response.ts, src/runtime/plugin.ts, test/basic.test.ts, test/fixtures/basic/nuxt.config.ts, test/fixtures/basic/package.json, test/fixtures/basic/server/api/csrf.ts, test/fixtures/basic/server/api/user.ts, test/fixtures/basic/tsconfig.json
In some cases, module writes too many logs about logged-out user on plugin initialisation due to incorrect typing of `FetchError`.
This PR fixes that by manually handling `FetchResponse` and 401/419 statuses to hide redundant logs under `debug` level.
=> fix(init): use raw fetch to handle errors on identity init

src/runtime/composables/useSanctumAuth.ts
Return the login response to handle custom logic on login.
In my case, the onLogin redirection route is dynamic, so I need to get the response to redirect to the intended url.
=> feat: return login response

src/runtime/interceptors/common/request.ts
Allows users to override `Accept` header value for custom scenarios, when non-JSON response is expected.
For example, when using StreamResponse in Laravel
```php
final class QuoteController extends Controller
{
public function __invoke(Request $request): JsonResponse|StreamedResponse
{
/** @var string $quote */
$quote = Inspiring::quotes()->random();
[$text, $author] = explode(' - ', $quote);
if ($request->header('Accept') === 'text/event-stream') {
return response()->eventStream(
function () use ($text, $author) {
yield $text;
}
);
}
$data = [
'text' => $text,
'author' => $author,
];
return response()->json($data);
}
}
```
In this case, in the Nuxt application we can make a request by using …
=> feat(client): allow overriding of Accept header per request

playground/nuxt.config.ts, src/config.ts, src/module.ts, src/runtime/composables/useSanctumAppConfig.ts, src/runtime/composables/useSanctumConfig.ts, src/runtime/httpFactory.ts, src/runtime/plugin.ts, src/runtime/server/api/proxy.ts, src/runtime/types/options.ts, src/runtime/utils/credentials.ts, src/runtime/utils/logging.ts
**Is your PR related to a specific issue/feature? Please describe and mention the issues.**
This PR introduces a Nuxt Server API as a proxy to the Laravel API to use a single entry point for all requests while taking care of all the headers and cookies needed to be sent to the target server.
This approach removes the need to set up `routeRules` and can be used without additional code changes on the client side. 
We introduce `serverProxy` config, which defines the catch-all endpoint properties:
- `enabled`: if false, the endpoint won't be used by the app
- `endpoint`: route of Nuxt server endpoint to handle all requests (catch-all)
- `baseUrl`: Laravel API baseUrl to be used for proxying
This implies that the main `baseUrl` used previously with Laravel API URL has to be replaced with …
=> feat: added nuxt server proxy endpoint

src/runtime/server/api/proxy.ts
Fixes #390 problem related to failing response read due to decompressed body on the server side.
=> fix: ignore reprocessed response content headers

src/runtime/composables/useSanctumAuth.ts
Closes #394 by adding an option to send user credentials without an immediate identity fetch call. Client code can later use `refreshIdentity` from `useSanctumAuth`.
=> feat: allow login without fetching an identity

src/runtime/composables/useLazySanctumFetch.ts, src/runtime/composables/useSanctumFetch.ts
Closes #416 by adding an optional argument for `useSanctumFetch` and `useLazySanctumFetch` to keep control over state management.
=> feat: support user-defined fetch key

src/runtime/composables/useLazySanctumFetch.ts, src/runtime/composables/useSanctumFetch.ts, src/runtime/utils/fetch.ts
Fixes #429 by resolving reactive options during fetch request rather than composable initialisation.
=> fix: resolve reactive options in useAsyncData
